name: Python CI

# Trigger the workflow on any push to the main branch or on pull requests targeting the main branch
on:
  push:
    branches:
        - main
  pull_request:   
    branches:
        - main  

jobs:
    test:
        runs-on: ubuntu-latest # container

        steps:
        # step 1: Check out the code from the repository
        - name: Check out code
          uses: actions/checkout@v2

        # step 2: Set up python environment
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        # step 3: Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # step 4: Run unit tests
        - name: Run tests
          run: pytest
